.TH GSDPARSER "1" "2016" "gsdparser" "User Commands"
.SH NAME
gsdparser \- PROFIBUS-DP GSD file parser based on pyprofibus
.SH SYNOPSIS
.B gsdparser
[\fIOPTIONS\fR]
.SH DESCRIPTION
PROFIBUS-DP GSD file parser based on pyprofibus
.SH OPTIONS
.TP
\fB\-h\fR|\-\-help
Print help information
.SH AUTHORS
Michael Buesch
