.TH PROFISNIFF "1" "2016" "profisniff" "User Commands"
.SH NAME
profisniff \- PROFIBUS-DP telegramm sniffer based on pyprofibus
.SH SYNOPSIS
.B profisniff
[\fIOPTIONS\fR]
.SH DESCRIPTION
PROFIBUS-DP telegramm sniffer based on pyprofibus
.SH OPTIONS
.TP
\fB\-h\fR|\-\-help
Print help information
.SH AUTHORS
Michael Buesch
