.TH PYPROFIBUS-LINUXCNC-HAL "1" "2016" "pyprofibus-linuxcnc-hal" "User Commands"
.SH NAME
pyprofibus-linuxcnc-hal \- PROFIBUS-DP HAL module for LinuxCNC based on pyprofibus
.SH SYNOPSIS
.B pyprofibus-linuxcnc-hal
[\fIOPTIONS\fR]
.SH DESCRIPTION
PROFIBUS-DP HAL module for LinuxCNC based on pyprofibus
.SH OPTIONS
.TP
\fB\-h\fR|\-\-help
Print help information
.SH AUTHORS
Michael Buesch
